### ISSUE TITLE
ArchLinux package

### ISSUE THREAD

**Issue by StuntsPT** [Oscillope/sbx-h6-rgb#1]
Hi @Oscillope ,
I'm just writing to let you know that your program works pretty well for my use case (turning off the headset LED on shutdown), and that I have built an ArchLinux AUR package for it: https://aur.archlinux.org/packages/sbx-h6-rgb-git
I took the liberty of adding a systemd service file to turn off the LED at shutdown, and turn it back on on startup (defaults to red). If I have the opportunity I will change this to read a config file, so that both statuses can be user configured.
I also noticed there is no LICENSE file in this repository. May I be so bold as to request one, so that there are nor redistribution issues?
Thank you so much for your effort in writing this program.

Best,

Francisco

**Comment by Oscillope** [comment]
Hi Francisco,
Thanks so much! I appreciate you making an AUR package for this. I've added a license file, apologies for that oversight.
If you'd like to submit a PR for your systemd service, I'd be happy to pull that into the main repo, though how you've done it in the AUR works just as well.

Cheers!
