### ISSUE TITLE
Trying to compile and I got the following "fatal error: hidapi/hidapi.h: No such file or directory"

### ISSUE THREAD

**Issue by alexvaque** [Oscillope/sbx-h6-rgb#3]
Thanks for your initiative . 

I have the latest Ubuntu version and I was trying to compile the project but I got the following, Do you have if the project is still working in new Linux versions, thanks 

I can not support to have the LED flashing and changing the color when I am using the headphones .

```
➜  sbx-h6-rgb git:(master) pwd
/tmp/a/sbx-h6-rgb
➜  sbx-h6-rgb git:(master) make  
gcc -lhidapi-libusb sbx-h6-ctl.c -o sbx-h6-ctl
sbx-h6-ctl.c:3:10: fatal error: hidapi/hidapi.h: No such file or directory
    3 | #include <hidapi/hidapi.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:5: ctl] Error 1
➜  sbx-h6-rgb git:(master) ls
99-sbx-h6-purple.rules  LICENSE  Makefile  README.md  sbx-h6-color-capture.pcapng  sbx-h6-ctl.c

```

**Comment by alexvaque** [comment]
after installing the following NEW packages 
  libhidapi-dev  and libhidapi-hidraw0

I got the folllowing 

```
 make 
gcc -lhidapi-libusb sbx-h6-ctl.c -o sbx-h6-ctl
/usr/bin/ld: /tmp/ccNMNXGH.o: in function `sbx_set_color':
sbx-h6-ctl.c:(.text+0x227): undefined reference to `hid_write'
/usr/bin/ld: sbx-h6-ctl.c:(.text+0x2a6): undefined reference to `hid_write'
/usr/bin/ld: sbx-h6-ctl.c:(.text+0x302): undefined reference to `hid_write'
/usr/bin/ld: /tmp/ccNMNXGH.o: in function `main':
sbx-h6-ctl.c:(.text+0x3ba): undefined reference to `hid_init'
/usr/bin/ld: sbx-h6-ctl.c:(.text+0x3fe): undefined reference to `hid_open'
/usr/bin/ld: sbx-h6-ctl.c:(.text+0x42c): undefined reference to `hid_exit'
/usr/bin/ld: sbx-h6-ctl.c:(.text+0x46e): undefined reference to `hid_close'
/usr/bin/ld: sbx-h6-ctl.c:(.text+0x473): undefined reference to `hid_exit'
collect2: error: ld returned 1 exit status
make: *** [Makefile:5: ctl] Error 1
```

**Comment by alexvaque** [comment]
Finally I fixed with the following GCC compile command and I got the binary, thanks for that project 

```
 gcc sbx-h6-ctl.c -o sbx-h6-ctl -lhidapi-libusb ```

**Comment by Oscillope** [comment]
Huh, interesting. On my system (`gcc 13.1.1`, `hidapi 0.14.0`) it works fine with the `-lhidapi-libusb` in either position, but I'm seeing online that the best practice is to include those linker arguments after the objects that require them. I will check in a fix for this to the makefile shortly. Thanks for pointing it out!

**Comment by alexvaque** [comment]
Finally It was not working

```

➜  sbx-h6-rgb git:(master) lsusb |grep "BlasterX"                   
Bus 003 Device 012: ID 041e:3255 Creative Technology, Ltd Sound BlasterX H6
➜  sbx-h6-rgb git:(master) ./sbx-h6-ctl -c "ff0000" -b 255 041e:3255
Error opening USB device 041e:3255

```
I have Ubuntu 22.04.2 LTS and the headphones are new from today . 
```
gcc version 11.3.0
libhidapi-hidraw0:amd64                       0.11.2-1
ii  libusb-1.0-0:amd64                            2:1.0.25-1ubuntu2                       amd64        userspace USB programming library


```

I will try to update my OS soon . 

Thanks again for your fast answer and give us that project to the community

**Comment by Oscillope** [comment]
You need to either run `sbx-h6-ctl` as root (e.g. with sudo), or create a udev rule which will make the device node accessible by a non-root group (e.g. `plugdev`, see also https://unix.stackexchange.com/a/85459).

**Comment by alexvaque** [comment]
:facepalm: sudo .. xD of course . Thanks . It is working 
```
 sudo ./sbx-h6-ctl -c "ffff00" -b 255 041e:3255 --brightness=255
set color to ffff00
```
@Oscillope Do you know if there are other open source projects for this headphones ? Or any idea what can be the next ? Is it necessary to use reverse engineering ? 



For me what I miss from Windows drivers is the Microphone tune up . I am working and using Zoom and my teammates can hearth me typing , in other headphones Logitech they can't not notice that I am typing . I think that I need to increase the cancellation of the microphone by default is not to much.
